"""Build the public demo from code-only fixtures. Never reads config or usage files."""
import json
import math
import shutil
import hashlib
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def synthetic_data():
    rows = []
    hourly_rows = []
    session_rows = []
    response_rows = []
    names = ('Atlas Code', 'Cedar Think', 'Orbit Local')
    for day in range(90):
        current = date(2026, 1, 1) + timedelta(days=day)
        leader = current.month - 1
        for index, model in enumerate(names):
            wave = 1 + .22 * math.sin(day * .41 + index) + .13 * math.cos(day * .83)
            tokens = round((120000 + day * 1600) * wave * (2.4 if index == leader else 1))
            # Fictional display values, not real model prices or recorded charges.
            cost = round(tokens / 1000000 * (2.8, 4.2, .4)[index], 4)
            rows.append(dict(date=current.isoformat(), host=('workstation', 'lab')[index % 2],
                             app=('Codex', 'Claude Code', 'Codex')[index], model=model,
                             tokens=tokens, requests=12 + day % 17 + index * 4,
                             cost_usd=f'{cost:.4f}'))
            morning_tokens = tokens // 3
            morning_cost = round(cost / 3, 4)
            hourly_rows.extend((dict(rows[-1], hour='09', tokens=morning_tokens,
                                     cost_usd=f'{morning_cost:.4f}'),
                                dict(rows[-1], hour='14', tokens=tokens-morning_tokens,
                                     cost_usd=f'{cost-morning_cost:.4f}')))
            for request in range(rows[-1]['requests']):
                # Fictional per-response measurements, with deliberate timing gaps.
                elapsed = round(5000 + 4000 * (1 + math.sin(day * .23 + request * .67 + index)), 2)
                output = 140 + (request * 29 + day * 11 + index * 31) % 700
                native = index != 1
                response_rows.append(dict(date=current.isoformat(), hour=('09', '14')[request % 2],
                                          host=rows[-1]['host'], app=rows[-1]['app'], model=model,
                                          output_tokens=output, duration_ms=elapsed if request % 13 else None,
                                          duration_source='native_log' if native else 'latency_ms',
                                          tps=output * 1000 / elapsed if request % 13 else None,
                                          first_token_ms=None if native or request % 7 == 0 else round(200 + 900 * (1 + math.sin(day + request)), 2)))
            # A fictional session spans up to ten days and can switch models.
            # Some days deliberately lack session detail to demonstrate coverage.
            if day % 11:
                session_rows.append(dict(rows[-1], session_key=hashlib.sha256(f'fictional-session-{day // 10}'.encode()).hexdigest(),
                                         project_key=hashlib.sha256(f'fictional-project-{day // 10 % 3}'.encode()).hexdigest(),
                                         project_name=('Demo dashboard','Fictional API','Demo dataset')[day // 10 % 3],
                                         session_title=('Build a sample dashboard', 'Review a fictional API', 'Explore a demo dataset')[day // 10 % 3] + f' · iteration {day // 10 + 1}',
                                         hours={'09':tokens//3,'14':tokens-tokens//3},
                                         tps_count=rows[-1]['requests'],tps_sum=rows[-1]['requests']*(20+index*15+day%8),tps_max=30+index*15+day%8,
                                         fresh_input_tokens=tokens//4, cache_read_tokens=tokens//2,
                                         cache_creation_tokens=tokens//10,
                                         output_tokens=tokens-tokens//4-tokens//2-tokens//10))
                if rows[-1]['app'] == 'Codex':
                    for field in ('tps_count', 'tps_sum', 'tps_max'):
                        session_rows[-1]['native_' + field] = session_rows[-1][field]
                        session_rows[-1][field] = 0
    return dict(generated_at='2026-04-01T00:00:00Z', rows=rows, hourly_rows=hourly_rows, session_rows=session_rows,
                response_rows=response_rows,host_date='2026-03-31',host_timezone='UTC',
                sources={name: dict(collected_at='2026-04-01T00:00:00Z', timezone='UTC')
                         for name in ('workstation', 'lab')},
                caveats=['All values and model/source names are deterministic fictional examples generated by build_demo.py.',
                         'Demo costs are invented, not pricing guidance. The real dashboard uses CC-Switch recorded estimates.',
                         'Leader labels show the top model and its cost for the selected day, week, or range; all-dates views show monthly leaders.',
                         'Animation only reveals existing marks; it does not simulate data collection.'])


def build():
    destination = ROOT / 'docs'
    destination.mkdir(exist_ok=True)
    page = (ROOT / 'web.html').read_text()
    page = page.replace('<title>Token usage</title>', '<title>TokenScope · Synthetic Demo</title>')
    page = page.replace('href="/web.css"', 'href="web.css"')
    page = page.replace('src="/session_usage.js"', 'src="session_usage.js"')
    page = page.replace('src="/response_speed.js"', 'src="response_speed.js"')
    page = page.replace('src="/i18n.js"', 'src="i18n.js"')
    # A changed reveal must replace cached CSS, including in the in-app browser.
    demo_style_version = hashlib.sha256((destination / 'demo.css').read_bytes()).hexdigest()[:12]
    page = page.replace('<script defer src="/web.js"></script>',
                        f'<link rel="stylesheet" href="demo.css?v={demo_style_version}"><script defer src="demo-data.js"></script><script defer src="web.js"></script>')
    page = page.replace('<body><main>', '<body><main><nav class="demo-nav"><a href="https://github.com/Crear12/tokenscope">◈ TokenScope</a><span class="demo-badge">SYNTHETIC DEMO</span><a href="https://github.com/Crear12/tokenscope#quick-start">Get the code ↗</a></nav>')
    page = page.replace('<h1>Token usage</h1>', '<p class="eyebrow">YOUR MODELS. ONE CLEAR VIEW.</p><h1>Tokens tell a story.<br>See the whole picture.</h1>')
    page = page.replace('id="show-sessions" type="checkbox"', 'id="show-sessions" type="checkbox" checked')
    page = page.replace('<div class="actions"><label>Refresh every', '<div class="actions live-controls" hidden><label>Refresh every', 1)
    page = page.replace('</header>', '<div class="demo-actions"><button id="replay">↻ Replay animation</button><a href="https://github.com/Crear12/tokenscope">View on GitHub ↗</a></div></header>', 1)
    page = page.replace('LAN viewers can change the shared refresh interval. Date and model filters affect only your browser. No requests overlap; refreshes run at clock-aligned boundaries while this command is running.',
                        'TokenScope · MIT licensed · This public demo contains no real usage. All interactions run in your browser. Animation respects reduced-motion preferences. Run the Python app locally to collect your own statistics.')
    (destination / 'index.html').write_text(page)
    (destination / 'demo-data.js').write_text('window.TOKEN_SCOPE_DEMO = ' + json.dumps(synthetic_data(), separators=(',', ':')) + ';\n')
    for name in ('web.js', 'web.css', 'session_usage.js', 'response_speed.js', 'i18n.js'):
        shutil.copyfile(ROOT / name, destination / name)
    (destination / '.nojekyll').touch()
    print('Built docs/ from synthetic fixtures only.')


if __name__ == '__main__':
    build()
